### ISSUE TITLE
Run seems to fail at the first attempt

### ISSUE THREAD

**Issue by plippe** [purescript-aws-sdk/gen#9]
```
/Users/pvinchon/Code/gen/output/Control.Monad.Aff/foreign.js:83
        throw error;
        ^

TypeError: Cannot read property 'constructor' of null
    at Object.isLeft (/Users/pvinchon/Code/gen/output/Control.Monad.Aff/index.js:75:119)
    at join (/Users/pvinchon/Code/gen/output/Control.Monad.Aff/foreign.js:720:16)
    at /Users/pvinchon/Code/gen/output/Control.Monad.Aff/foreign.js:780:19
    at /Users/pvinchon/Code/gen/output/Control.Monad.Aff/foreign.js:669:29
    at runEff (/Users/pvinchon/Code/gen/output/Control.Monad.Aff/foreign.js:80:7)
    at run (/Users/pvinchon/Code/gen/output/Control.Monad.Aff/foreign.js:496:15)
    at /Users/pvinchon/Code/gen/output/Control.Monad.Aff/foreign.js:333:19
    at drain (/Users/pvinchon/Code/gen/output/Control.Monad.Aff/foreign.js:120:9)
    at Object.enqueue (/Users/pvinchon/Code/gen/output/Control.Monad.Aff/foreign.js:141:11)
    at /Users/pvinchon/Code/gen/output/Control.Monad.Aff/foreign.js:330:27
* ERROR: Subcommand terminated with exit code 1
make: *** [run] Error 1
```

`make clean build run` will fail with  ^^
`make run`, after failed attempt, will succeed

**Comment by plippe** [comment]
Issue related to parTraverse, fix incoming

**Comment by plippe** [comment]
https://github.com/purescript-aws-sdk/gen/pull/17
